version: "3.9"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./dev-db-init.sql:/docker-entrypoint-initdb.d/dev-db-init.sql
